<?php
require('config.php');

$hostname = php_uname('n');

echo "*** Targets ***

probe = FPing

menu = Top
title = Smokeping
remark = Powered by $hostname, generated by Sean

# Generated by Sean
# https://github.com/Sea-n/smokeping-config-generator

";
echo createConfig(CONFIG);


function createConfig($data, string $prefix = '', int $seq = 1): string {
	$result = '';
	foreach ($data as $key => $val) {
		if (is_array($val)) {
			$result .= str_repeat('+', $seq) . " $key\nmenu = $key\ntitle = $key\nhost = " . getHosts("$prefix/$key", $val) . "\n\n";
			$result .= createConfig($val, "$prefix/$key", $seq+1);
		} else
			$result .= str_repeat('+', $seq) . " $key\nmenu = $key\ntitle = $key\nhost = $val\n\n";
	}
	return $result;
}

function getHosts(string $prefix, array $config): string {
	$result = '';
	foreach ($config as $key => $val) {
		if (is_array($val))
			$result .= getHosts("$prefix/$key", $val) . " \\\n";
		else
			$result .= "$prefix/$key \\\n";
	}
	$result = substr($result, 0, -3);
	return $result;
}
